# Generated by Django 4.2.4 on 2023-08-24 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="processing...", max_length=250)),
                ("max", models.IntegerField(default=0)),
                ("next", models.URLField(null=True)),
            ],
        ),
    ]
