# Generated by Django 4.2.5 on 2023-09-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created"]},
        ),
        migrations.AddField(
            model_name="message",
            name="reply",
            field=models.BooleanField(default=False),
        ),
    ]
