# Generated by Django 4.2.5 on 2023-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_message_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefile",
            name="text",
            field=models.TextField(default="", max_length=3000),
            preserve_default=False,
        ),
    ]
