# Generated by Django 4.2.5 on 2023-09-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_messagefile_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagefile",
            name="text",
            field=models.TextField(max_length=6000),
        ),
    ]
